services:
  db:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  cdurgun-api:
    container_name: cdurgun-api
    image: cdurgun/cdurgun-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped
  cdurgun-react:
    container_name: cdurgun-react
    image: cdurgun/cdurgun-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8080
    ports:
      - "3000:5173"
    depends_on:
      - cdurgun-api
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
